title: "Physics 102: Electricity and Magnetism"
description: "Spring 2026 â€¢ Course website"
theme: just-the-docs

url: "https://caganaksak.github.io"
baseurl: "/phys102-spring2026"

search_enabled: true

aux_links:
  "GitHub repo":
    - "https://github.com/caganaksak/phys102-spring2026"

# Optional: show "last updated" on pages
last_edit_timestamp: true
last_edit_time_format: "%Y-%m-%d"
